name: Run Integration Tests
on: [push]

jobs:
   AKS-method-integration-test:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout Source Code
           id: checkout-code
           uses: actions/checkout@v2
         - name: Npm Install and Build
           id: npm-build
           run: |
              npm install
         - name: Build
           run: npm run build
         - name: Set Context
           uses: aamgayle/k8s-set-context@v4.8
           with:
              cluster-type: 'aks'
              method: 'service-account'
              k8s-url: ${{ secrets.K8S_URL }}
              k8s-secret: ${{ secrets.K8S_SECRET }}

         - name: Vertify Results
           run: |
              echo "$(<$KUBECONFIG)"
